[project]
name = "nunchaku-klein"
description = "NOTE: In order to use Direct K/V nodes, you'll have to install our extended version of Vitoom Nunchaku. Check README for more detail. ComfyUI custom node for Nunchaku Flux.2 Klein, independent of official ComyUI-Nunchaku. Requires tonera's Vitoom Nunchaku. Added features such as Klein Enhancer ported, or compatibility versions."
version = "0.7.0"
license = {file = "LICENSE"}

# classifiers = [
#     "Operating System :: Microsoft :: Windows",
#     "Operating System :: POSIX :: Linux",
#     "Environment :: GPU :: NVIDIA CUDA",
# ]
dependencies = []

[project.urls]
Repository = "https://github.com/tom-m-2020/ComfyUI-Nunchaku-Klein"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/tom-m-2020/ComfyUI-Nunchaku-Klein/wiki"
"Bug Tracker" = "https://github.com/tom-m-2020/ComfyUI-Nunchaku-Klein/issues"

[tool.comfy]
PublisherId = "tom-m"
DisplayName = "ComfyUI-Nunchaku-Klein"
Icon = ""
includes = []
# "requires-comfyui" = ">=0.29.0"  # ComfyUI version compatibility
