[project]
name = "nunchaku-klein"
description = "NOTE: Some of Enhancer nodes are still not implemented yet. Check README for details. ComfyUI custom node for Nunchaku Flux.2 Klein, independent of official ComyUI-Nunchaku. Requires tonera's Vitoom Nunchaku. Added features such as Klein Enhancer ported."
version = "0.2.3"
license = {file = "LICENSE"}

classifiers = [
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Environment :: GPU :: NVIDIA CUDA",
]
dependencies = []

[project.urls]
Repository = "https://github.com/Tom-M-Git/ComfyUI-Nunchaku-Klein"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/Tom-M-Git/ComfyUI-Nunchaku-Klein/wiki"
"Bug Tracker" = "https://github.com/Tom-M-Git/ComfyUI-Nunchaku-Klein/issues"

[tool.comfy]
PublisherId = "tom-m"
DisplayName = "ComfyUI-Nunchaku-Klein"
Icon = ""
includes = []
# "requires-comfyui" = ">=0.29.0"  # ComfyUI version compatibility
